@startuml
class ButtonController {
    - OnEnable() : void
    GotoVipRoom() : void
    GotoTitleButton() : void
    BetUpButton() : void
    BetDownButton() : void
    CanBetUpDown() : void
    canDoubleDown : bool
    StartButton() : void
    StandButton() : void
    RetryButton() : void
    HitButton() : void
    DoubleDownButton() : void
    SurrenderButton() : void
    StartWindowButtons() : void
    ResultWindowButtons() : void
}
MonoBehaviour <|-- ButtonController
ButtonController --> "gotoVipRoomButton" Button
ButtonController --> "gotoTitleButton" Button
ButtonController --> "betUpButton" Button
ButtonController --> "betDownButton" Button
ButtonController --> "startButton" Button
ButtonController --> "standButton" Button
ButtonController --> "retryButton" Button
ButtonController --> "hitButton" Button
ButtonController --> "doubleDownButton" Button
ButtonController --> "surrenderButton" Button
ButtonController --> "gameDirector" GameDirector
ButtonController --> "playerController" PlayerController
ButtonController --> "dealerController" DealerController
@enduml
