@startuml
class DealerController {
    {static} bet : int
    + Bet : int <<get>> <<set>>
    # <<override>> Awake() : void
    + <<override>> GameStart() : void
    + <<override>> ResetCardsInfo() : void
    UpCard() : void
    + DrawDealer() : void
    + Dividend : int <<get>>
    + DividendToPlayer() : void
    + DividendResult(judgeEnum:GameDirector.JudgeEnum) : void
}
CharacterBase <|-- DealerController
DealerController --> "playerController" PlayerController
DealerController --> "dividendText" Text
@enduml
