@startuml
class DealerController {
    {static} bet : int
    + Bet : int <<get>> <<set>>
    + DividendMultiplier : float <<set>>
    + Dividend : int <<get>>
    + <<override>> GameStart() : void
    + <<override>> ResetCardsInfo() : void
    UpCard() : void
    + DrawDealer() : void
}
CharacterBase <|-- DealerController
@enduml
