@startuml
class TitleManager {
    Start() : void
    GotoMain() : void
    GameRule() : void
    BackToTitle() : void
}
MonoBehaviour <|-- TitleManager
TitleManager --> "gotoMainButton" Button
TitleManager --> "gameRuleButton" Button
TitleManager --> "backToTitleButton" Button
TitleManager --> "gameRulePanel" GameObject
@enduml
