@startuml
class CharacterBase {
    direction : float
    + <<virtual>> GameStart() : void
    + ResetCardsInfo() : void
    CharacterCardSpritesRemove() : void
    CharacterCardSpritesAdd(cardPos:Vector2) : void
    CharacterScoreSum() : bool
}
MonoBehaviour <|-- CharacterBase
CharacterBase --> "characterTransform" Transform
CharacterBase --> "gameDirectorObject" GameObject
CharacterBase --> "cardPrefab" SpriteRenderer
@enduml
