@startuml
class GameDirector {
    Start() : void
    + GameStart() : void
    + Stand() : void
    + ResetField() : void
    + Judgement() : void
}
MonoBehaviour <|-- GameDirector
GameDirector --> "startButton" GameObject
GameDirector --> "standButton" GameObject
GameDirector --> "retryButton" GameObject
GameDirector --> "playerButtons" GameObject
GameDirector --> "playerController" PlayerController
GameDirector --> "dealerController" DealerController
GameDirector --> "trumpController" TrumpController
@enduml
